# Generated by Django 3.0.4 on 2020-03-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('sex', models.CharField(choices=[('2', '女'), ('1', '男')], max_length=1, verbose_name='性别')),
                ('head_img', models.FileField(upload_to='heads/%Y%m%d%H%M%S/')),
                ('sign_info', models.CharField(max_length=100, verbose_name='sign')),
                ('cares', models.CharField(default='', max_length=255, verbose_name='关注')),
                ('sign_dao', models.CharField(default='', max_length=100, verbose_name='签到')),
                ('my_pub', models.CharField(default='', max_length=255, verbose_name='发布')),
                ('my_care', models.CharField(default='', max_length=255, verbose_name='发布')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.User')),
            ],
            options={
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='User_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cares', models.CharField(max_length=100, null=True, verbose_name='123')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.User')),
            ],
            options={
                'db_table': 'Care',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('url', models.FileField(upload_to='files/%Y%m%d%H%M%S/')),
                ('introduce', models.CharField(max_length=100, verbose_name='介绍')),
                ('time', models.CharField(max_length=20, verbose_name='时间')),
                ('good', models.CharField(default='', max_length=100, verbose_name='赞')),
                ('share', models.CharField(default='', max_length=100, verbose_name='分享')),
                ('comments', models.CharField(default='', max_length=100, verbose_name='评论')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.User')),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='', max_length=200, verbose_name='时间')),
                ('time', models.CharField(default='', max_length=20, verbose_name='时间')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.User')),
                ('pubs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.Pub')),
            ],
            options={
                'db_table': 'commnets',
            },
        ),
    ]
