# Generated by Django 3.0.4 on 2020-03-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeyepy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Sign_dao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_num', models.CharField(max_length=100, null=True, verbose_name='123')),
                ('time', models.CharField(max_length=100, null=True, verbose_name='123')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeyepy.User')),
            ],
            options={
                'db_table': 'sing_dao',
            },
        ),
    ]
